service: rs-doctors-back
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ DoctorsTable, Arn ]
            - Fn::GetAtt: [ PatientsTable, Arn ]
            - Fn::GetAtt: [ ScheduleTable, Arn ]
  httpApi:
    cors: true
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
          - ''
          - - 'https://cognito-idp.'
            - '${opt:region, self:provider.region}'
            - '.amazonaws.com/'
            - Ref: CognitoUserPool
        audience:
          - Ref: CognitoUserPoolClient
  environment:
    DOCTORS_TABLE: ${self:custom.doctorsTable}
    PATIENTS_TABLE: ${self:custom.patientsTable}
    SCHEDULE_TABLE: ${self:custom.scheduleTable}

custom:
  esbuild:
    exclude:
      - '@aws-sdk/*'
  doctorsTable: doctors-table-${self:provider.stage}
  patientsTable: patients-table-${self:provider.stage}
  scheduleTable: schedule-table-${self:provider.stage}
  userPool: user-pool-${self:provider.stage}
  userClient: user-client-${self:provider.stage}
  attachmentsBucket: doctors-attachments-s3-bucket-${self:provider.stage}
  identityPool: doctors-identity-pool-${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-esbuild

# Services
functions:
  - ${file(./sls/services/doctors.yml)}
  - ${file(./sls/services/patients.yml)}
  - ${file(./sls/services/schedule.yml)}

resources:
  - ${file(./sls/resources/dynamo.yml)}
  - ${file(./sls/resources/cognito.yml)}
  - ${file(./sls/resources/s3.yml)}
